export const GET_TRANSACTION = 'GET_TRANSACTION';
export const DETAIL_TRANSACTION = 'DETAIL_TRANSACTION';
export const FILTER_TRANSACTION = 'FILTER_TRANSACTION';
export const SORT_TRANSACTION = 'SORT_TRANSACTION';